spring:
  application:
    name: np-web-server
  datasource:
    url: jdbc:mysql://localhost:3306/interauto_db
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

udp:
  multicast:
    address: 239.255.255.250
    port: 4446

server:
  host: localhost
  port: 8080

node:
  id: 1

logging:
  level:
    root: INFO
    com.yaeby.np_lab_2: DEBUG
    com.yaeby.np_lab_2.udp.RaftLeaderElectionService: DEBUG

manager:
  server:
    host: ${MANAGER_HOST:localhost}
    port: 9090
    protocol: http
    base-url: ${manager.server.protocol}://${manager.server.host}:${manager.server.port}
