spring:
  application:
    name: np-rabbitmq-manager
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  queue:
    name: scraper_queue
  exchange:
    name: scraper_exchange
  routing:
    key: scraper_routing_json_key

server:
  port: 9090

np-web-server:
  host: localhost
  port: 8080
  protocol: http
  base-url: ${np-web-server.protocol}://${np-web-server.host}:${np-web-server.port}