spring:
  application:
    name: np-rabbitmq-manager
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

rabbitmq:
  queue:
    name: scraper_queue
  exchange:
    name: scraper_exchange
  routing:
    key: scraper_routing_json_key

server:
  port: 9090

np-web-server:
  host: ${NP_WEB_SERVER_HOST:localhost}
  port: 8080
  protocol: http
  node: 1

ftp:
  host: ${FTP_HOST:localhost}
  port: 21
  user: testuser
  password: testpass