version: '3.8'
services:
  app1:
    container_name: node1
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/interauto_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SERVER_PORT=8080
      - NODE_ID=1
      - MANAGER_SERVER_HOST=host.docker.internal
    depends_on:
      db:
        condition: service_healthy

  app2:
    container_name: node2
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/interauto_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SERVER_PORT=8081
      - NODE_ID=2
      - MANAGER_SERVER_HOST=host.docker.internal
    depends_on:
      db:
        condition: service_healthy

  app3:
    container_name: node3
    build: .
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/interauto_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SERVER_PORT=8082
      - NODE_ID=3
      - MANAGER_SERVER_HOST=host.docker.internal
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=interauto_db
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
      timeout: 3s

volumes:
  mysql-data: