version: '3.8'
services:
  app:
    container_name: manager
    build: .
    ports:
      - "9090:9090"
    environment:
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SPRING_RABBITMQ_HOST=host.docker.internal
      - FTP_HOST=host.docker.internal
      - NP_WEB_SERVER_HOST=host.docker.internal